name: Building

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]  #[3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest miniconda. The "test" environment is activated 
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install pytest
        python setup.py install
        conda install -c pytorch faiss-cpu
        
    - name: Test with pytest
      run: |
        make test