name: Building

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]  #[3.8, 3.9, 3.10] # The test fails for py 3.10 as of April 2023. Should be updated some day.

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest miniconda. The "test" environment is activated 
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash -l {0}    # to activate conda
      run: |
        pip install pytest
        python setup.py install
        #conda install -c pytorch faiss-cpu

        # After the bug of 1.7.4 is fixed, let's use the latest version. As of now, install the old version for each os.
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          conda install -c pytorch faiss-cpu==1.7.3
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          conda install -c pytorch faiss-cpu==1.7.3
        elif [ "${{ matrix.os }}" = "windows-latest" ]; then
          conda install -c pytorch faiss-cpu==1.7.4
        fi
        
    - name: Test with pytest
      shell: bash -l {0}   # to activate conda
      run: |
        make test